deploy:
  provider: firebase
  token:
        secure: "o9acRJfHMPPT80dD3y9G4V5rrxarmL8cAU1hG9yuMlHq4BbTUpHhdi+NzsSITthizOo2uAy9odlCLO3N8Kb/9Ws2HAmowoW1NVXGosyxK7xekppo0PYjPCI/mQf4+joVYl/FBzE0qITlxZ034xDKSnYAPKFTo6zpOH7jrhZHvbOGZaBlAmXvbeIWhOoRVprvYJjfwvLvBtujr8Ysp2Uph4UhYV5BMl/QsLa2vh85KWDmBKC6XdqEROQWHzrKChgrnZgcP4Xl4iIBlIn/AAw09ofZrHGz9RSnmB5uiyuDV5Z70df4IAezxPnaRyJjPJL+yckx1O56AEhKR+i2ymluDtc9GFlCKTU29pNrFb4lcBFVj+8ZWiLvl4BrFHsx/ZA1PEjZVcbKr6NHpn+2C7dDP9mEpyEBb2thaXDYsWeLqiF9olqVbqI0+1arNFbX7EAGFkSruMdiIoLN+kYr++/RdZMcE55EfVB3uiZst8g6+ZwQ5b8oqusQzICbJmHO9iwU79TywR4or0oivg940iZ6H3SOFjzmbxbFCmDfTs+9pJBlRct/Wb1F4Zi7Woqsbpncjmpf4ZsOdbqxhn3yATydjsPd2xw/9Vr4BO6s6U7eOsHDoE07JYJv5ox3G7D9napDxBD6Msdth4Z1EisR8DWGuLSxy/e79qsHyulDxUAvGYs="
  project: "dream-c5c23"
  message: "travis ci deploy"
